import keyMirror from "keyMirror";

export default keyMirror({
	RESET_HOSTS:null,
	FETCH_FAILURE: null,
	FETCH_SUCC: null,
	FETCH: null,
	ADD_GROUP: null,
	DEL_GROUP: null,
	CHANGE_GROUP_NAME: null,
	CHANGE_BRANCH_NAME: null,
	ADD_BRANCH: null,
	DEL_BRANCH: null,
	TOGGLE_BRANCH_DIS: null,
	TOGGLE_GROUP_DIS: null,
	DRAWERSTATUS: null,
	DISABLE_ALL: null,
	ADD_RULE: null,
	DEL_RULE: null,
	TOGGLE_RULE_DIS: null,
	UPDATE_RULE: null,
	TOGGLE_FLOD: null,
	SWITCH_BRANCH: null,
	SWITCH_GROUP: null,
	SWITCH_RULE: null,
	UPDATE_CURRENT_RULE: null,
});
